[tool.poetry]
name = "vfp"
version = "0.2.0"
description = "Calculate neutron and x-ray reflectivity profiles via physical volume fraction profiles."
authors = ["Alexander Armstrong <sandyjoarmstrong@hotmail.com>", 
           "Rebecca Welbourn"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [{include = "vfp", from="src"}]

[tool.poetry.dependencies]
python = ">=3.12, <4.0"
matplotlib = ">=3.10.0"
numpy = ">=2.1"
scipy = ">=1.14"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
jupyter = "^1.0.0"
ruff = "^0.9.3"
black = "^24.10.0"
tqdm = "^4.67.1"
myst-nb = "^1.2.0"
sphinx-autoapi = "^3.4.0"
sphinx-rtd-theme = "^3.0.2"
deptry = "^0.23.0"
sphinx-math-dollar = "^1.2.1"

[tool.poetry.group.refnx.dependencies]
refnx = {version = ">=0.1.51", optional = true}

[tool.poetry.group.refl1d.dependencies]
# installed bumps and refl1d via:
# pip install git+https://github.com/bumps/bumps.git@v1.0.0a15 - I cannot get poetry to do this?
# bumps = {git = "https://github.com/bumps/bumps.git", tag = "v1.0.0a15", optional = true}
# refl1d = {git = "https://github.com/reflectometry/refl1d.git", tag = "v1.0.0a16", optional = true}
# refl1d = {version = "^0.8.16", optional = true}
# bumps = {version = "^0.9.3", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 78
target-version = ['py312']
extend-exclude = "docs/*"

[tool.isort]
py_version = 312
profile = "black"
line_length = 78
extend_skip = ["docs"]

[tool.ruff]
src = ["src"]
target-version = "py312"
line-length = 78

[tool.ruff.lint]
select = [
    "A",    # prevent using keywords that clobber python builtins
    "B",    # bugbear: security warnings
    "E",    # pycodestyle
    "F",    # pyflakes
    "W",    # pycodestyle
    "N",    # pep8-naming
    "ISC",  # implicit string concatenation
    "UP",   # alert you when better syntax is available in your python version
    "RUF",  # the ruff developer's own rules
    "PLC",   # pylint
    "PLE",   # pylint
    "PLR",   # pylint
    "PLW",   # pylint
    "NPY",  # numpy
    "DTZ",  # datetimez
    "PLW1514", # unspecified-encoding (in preview)
]

# Exclude specific paths or files
exclude = ["tests/"]
